name: CI

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  Run_all_test:
    name: Run all python tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up python
        run: python3 -m pip install -r requirements.txt

      - name: Run tests
        run: |
          set -e
          python3 run_tests.py